language: php
php:
  - '7.2'
sudo: false
before-install:
- composer self-update

install:
- composer install
- cp app/config/parameters.yml.dist app/config/parameters.yml
- php bin/console doctrine:database:drop --force
- php bin/console doctrine:database:create
- php bin/console doctrine:schema:create


script:
- phpunit