<?php

namespace AppBundle\Repository;

/**
 * EmailConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailConversationRepository extends \Doctrine\ORM\EntityRepository
{
}
