<?php

namespace AppBundle\Repository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
